name = "vidscreener"
main = "wrangler/index.ts"
compatibility_date = "2026-03-12"
account_id = "78227b31bb029c09f05fe99b4d9b77cf"

[vars]
JWT_SECRET = "supersecret-1234567890-securekey"

[[d1_databases]]
binding = "DB"
database_name = "vidscreener"
database_id = "0f91fdc6-2616-4ede-b7a6-63543e8162a8"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "vidscreener"
